# Generated by Django 5.0.1 on 2024-01-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_blooddonation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodDonation',
        ),
    ]
