# Generated by Django 5.0.1 on 2024-01-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_blooddonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='units_collected',
            field=models.IntegerField(default=0),
        ),
    ]
