# Generated by Django 5.0.1 on 2024-01-19 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_bloodinventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=100)),
                ('units_shipped', models.PositiveIntegerField()),
                ('shipment_date', models.DateField(auto_now_add=True)),
                ('blood_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.bloodinventory')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_shipments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
