# Generated by Django 5.0.1 on 2024-01-19 03:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_bloodshipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodshipment',
            name='sender',
        ),
        migrations.AddField(
            model_name='bloodshipment',
            name='destination',
            field=models.CharField(default='Emergency Room', max_length=255),
        ),
        migrations.AlterField(
            model_name='bloodshipment',
            name='shipment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bloodshipment',
            name='units_shipped',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
