# Generated by Django 5.0.1 on 2024-01-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_bloodshipment_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodshipment',
            name='sender_name',
            field=models.CharField(default='Staff', max_length=255),
        ),
    ]
