# Generated by Django 5.0.1 on 2024-01-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_bloodshipment_sender_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issn', models.CharField(max_length=20)),
            ],
        ),
    ]
