# Generated by Django 5.0.1 on 2024-01-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_medicaljournal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalJournal',
        ),
    ]
